import unittest
import os

from HTMLTestRunnerCN import HTMLTestReportCN

if __name__ == '__main__':
    curfilename = os.path.basename(__file__).split('.')[0]

    loader = unittest.TestLoader()
    suite = loader.discover('..\\Src\\test\\case')
    '''
    runner = unittest.TextTestRunner(verbosity=1)
    runner.run(suite)

    '''
    with open('..\\Report\\' + str(curfilename) + '.html', 'wb') as f:
        runner = HTMLTestReportCN(stream=f,
                                  title='First Test Report',
                                  description='generated by ZCF.',
                                  verbosity=2)
        runner.run(suite)
