import unittest
from subclass import SubTest
from HTMLTestRunnerCN import HTMLTestReportCN

if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(SubTest))
    runner = unittest.TextTestRunner(verbosity=1)
    runner.run(suite)

    '''
    with open('HTMLReport.html', 'wb') as f:
        runner = HTMLTestReportCN(stream=f,
                                  title='MathFunc Test Report',
                                  description='generated by HTMLTestRunner.',
                                  verbosity=2)
        runner.run(suite)
    '''